### ISSUE TITLE
Limit display on the AI Watch and Org Watch homepages to top 300 + ties with the 300th

### ISSUE THREAD

**Issue by vipulnaik** [riceissa/aiwatch#98]
https://orgwatch.issarice.com/#positions-grouped-by-person currently shows 4711 persons. That's a lot, and we expect it to grow as @sebastiansanchez123 adds more data.

So here's a thought! Limit the default homepage display for persons and organizations to the top 1000 by the sorting key (which for persons is number of organizations and for organizations is the number of person) but also include entries tied with the 100th. So e.g. if the top 900 persons have 3 or more organizations and the next 700 have 2, then show all 900 + 700 = 1600.

For organizations, this would be a non-binding constraint as we have fewer than 1000 organizations, so all of them are being shown right now. For persons, this constraint would already be binding.

Write the code so that the "1000" can be changed to another number easily.

Maybe allow a `display=full` option similar to what we have on DLW.

@riceissa found https://stackoverflow.com/a/30615764/3422337 that uses a subquery to accomplish the goal in a single MySQL query.

**Comment by riceissa** [comment]
There are only 366 persons with 2 or more orgs, so having the cutoff at 1000 would mean we aren't displaying any fewer people, since the 1000th person has 1 org. (Actually, there are a small number of people with 0 orgs, but it doesn't really affect the length of the page.) So even for people, this would be a "non-binding constraint", which makes this strategy for cutting down on the length of the page kinda useless...

Maybe we can just use a hard cutoff, like "limit 1000"? Or pick a smaller number like 300 (so that we will end up showing the 366 people using your strategy)?

**Comment by vipulnaik** [comment]
Thanks @riceissa -- how about wee go with a smaller number of 300, while using the strategy originally proposed in this issue?

**Comment by riceissa** [comment]
Sounds good, let me see if I can get the right SQL query

**Comment by riceissa** [comment]
This is now done

- https://orgwatch.issarice.com/#positions-grouped-by-person
- https://orgwatch.issarice.com/?display=full#positions-grouped-by-person

(it's also working for orgs, but limit is too high so not enforced)

**Comment by vipulnaik** [comment]
LGTM, thanks @riceissa!
